[package]
name = "apisentinel-auth"
version.workspace = true
edition.workspace = true

[dependencies]
common = { path = "../../crates/common" }
auth_core = { path = "../../crates/auth_core" }
tokio = { workspace = true }
