services:
  postgres:
    image: postgres:16
    container_name: apisentinel-postgres
    environment:
      POSTGRES_DB: apisentinel
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
    volumes:
      - apisentinel_pgdata:/var/lib/postgresql/data

volumes:
  apisentinel_pgdata:
